done hw05
artemiyokulov/otus-golang-1 pull request #6
Opened 2024-05-11 20:40 UTC by artemiyokulov

2024-05-12 16:29 UTC, dshemin requested changes

2024-05-12 16:29 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	neededWorkers := min(n, int(tasksCount))
Критично:

Внимательно посмотрите задание:
```
количество создаваемых горутин не должно зависеть от числа заданий, т.е. функция должна запусать n горутин для параллельно обработки заданий и, возможно, еще несколько вспомогательных горутин;
```

2024-05-12 16:29 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	tasksCount := int32(len(tasks))
Важно:

Нужно добавить проверку на количество воркеров. Оно должно быть > 0

2024-05-12 16:29 UTC, dshemin commented on hw05_parallel_execution/run.go
> +				f, ok := <-fifo
Важно:

Можно просто:
```
for f := range fifo {
    // ...
}
```

2024-05-12 16:29 UTC, dshemin commented on hw05_parallel_execution/run.go
> +				if atomic.LoadInt32(&recievedTasks) > atomic.LoadInt32(&tasksCount) {
Важно:

Для чего нам эта проверка?

2024-05-12 17:22 UTC, artemiyokulov commented on hw05_parallel_execution/run.go
> +				if atomic.LoadInt32(&recievedTasks) > atomic.LoadInt32(&tasksCount) {
лишняя, убрал

2024-05-12 17:23 UTC, artemiyokulov commented on hw05_parallel_execution/run.go
> +	neededWorkers := min(n, int(tasksCount))
понял, поправил

2024-05-12 17:23 UTC, artemiyokulov commented on hw05_parallel_execution/run.go
> +	tasksCount := int32(len(tasks))
добавил

2024-05-12 17:23 UTC, artemiyokulov commented on hw05_parallel_execution/run.go
> +				f, ok := <-fifo
спасибо, буду знать

2024-05-12 17:23 UTC, artemiyokulov commented
@dshemin  внес правки

2024-05-13 14:09 UTC, dshemin approved these changes

2024-05-13 14:09 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	tasksCount := int32(len(tasks))
Проверки нет.

2024-05-13 14:09 UTC, dshemin commented on hw05_parallel_execution/run.go
> +				atomic.AddInt32(&recievedTasks, 1)
Важно:

Нам не надо считать задачи.

2024-05-14 13:35 UTC, artemiyokulov commented on hw05_parallel_execution/run.go
> +				atomic.AddInt32(&recievedTasks, 1)
https://github.com/artemiyokulov/otus-golang-1/blob/hw05_parallel_execution/hw05_parallel_execution/run.go#L17 вот здесь проверка

2024-06-02 13:23 UTC, merged