hw06 done
artemiyokulov/otus-golang-1 pull request #9
Opened 2024-06-06 18:33 UTC by artemiyokulov

2024-06-06 18:51 UTC, artemiyokulov commented
@dshemin тесты не стабильны, на локальной машине выполняются все меньше чем за 250 см 

go test -v -race -count=100 .

2024-06-10 04:58 UTC, dshemin requested changes
Критично:

Код сильно переусложнён. Тут можно в разы проще.

Для начала, поймите что Вы выстраиваете конвер сходный с конвеерами в bash (cat file | sort | unique | head -n 5) где каждый шаг выполняет некую работу и передаёт её дальше. Попробуйте это выразить в коде.

После этого, у нас есть усложнение - канал закрытия. Чтобы его обработать надо обернуть каждый шаг в горутину в которой:
- создать выходной канал
- запустить бесконечный цикл с select в котором передавать обслуживать канал закрытия и канал с входными данными. Если закрыли - завершить обработку шага. Если пришли данные - отправить в шаг.

2024-06-10 05:27 UTC, artemiyokulov commented
@dshemin  я возможно не правильно понял комментарий ваш, 

execChain - это и есть pipe, там используется рекурсия, чтобы передать результат исполнения на следующий шаг
там как перед выполнением шага происходит проверка через select (цикл в данном случае не нужен), и если есть сообщение в done, то не выполняем следующий шаг

в ExecutePipeline происходит создание канала, который и возвращается и запуск управляющий горутины.
далее на каждый элемент происходит запуск pipe в отдельной горутине.

запускать горутину на каждый шаг излишне ведь, так как шаги исполняются последовательно, и в любом случае происходит ожидание.

сейчас для 5 элементов 1,2,3,4,5 происходит запуск 6 горутин. 1 основная и 5 на каждый элемент, которые и ведут элемент по конвееру последовательно, но все в параллель

2024-06-10 05:41 UTC, artemiyokulov commented
я осознанно не генерировал горутины на каждый запуск каждого стейджа каждого элемента.
в таком варианте массив из 1000 элементов и 1000 стейджей, породит 1 млн+ горутин

в моем решении будет 1001 горутина

2024-06-12 16:42 UTC, dshemin commented
У многих возникают проблемы с эти заданием, поэтому мучить не буду. Посмотрите внимательно на предложенные вариант решения с дополнительной горутиной на каждый шаг:
```
func ExecutePipeline(in In, done In, stages ...Stage) Out {
	if in == nil {
		return nil
	}

	out := in
	for _, stage := range stages {
		out = executeStage(stage(out), done)
	}

	return out
}

func executeStage(in In, done In) Out {
	out := make(Bi)

	go func() {
		defer func() {
			close(out)
			for len(in) > 0 {
				<-in
			}
		}()

		for data := range in {
			if isTerminated(done) {
				return
			}

			out <- data
		}
	}()

	return out
}

func isTerminated(done In) bool {
	if done != nil {
		if _, ok := <-done; !ok {
			return true
		}
	}

	return false
}
```

2024-06-13 13:42 UTC, artemiyokulov commented
@dshemin  спасибо, решение с точки зрения написания кода изящное и лаконичное, я бы до такой конструкции сам не додумался бы точно
 
```
out := in
	for _, stage := range stages {
		out = executeStage(stage(out), done)
	}
```

Но simple_case выполняется в данном решении в два раза медленнее, чем в моем (0.8 против 0.4).

Я сделал тесты стабильно проходящими, подглядел у вас, и заменил select на isTerminated, чтоб исключить рандом

2024-06-15 05:26 UTC, dshemin approved these changes

2024-06-15 10:01 UTC, merged